package employee.management;

import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.sql.*;
import java.time.*;
import java.time.format.*;

/**
 * Exports employee data to a proper Excel-compatible CSV file
 * (opens perfectly in Excel with all columns formatted).
 * No external jar needed — uses pure Java file writing.
 */
public class ExcelExporter {

    public static void exportEmployees(JFrame parent) {
        // File chooser
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Save Employee Report");
        String defaultName = "EMS_Employees_" +
            LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")) + ".csv";
        fc.setSelectedFile(new File(defaultName));
        fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("CSV Excel File (*.csv)", "csv"));

        if (fc.showSaveDialog(parent) != JFileChooser.APPROVE_OPTION) return;

        File file = fc.getSelectedFile();
        if (!file.getName().endsWith(".csv")) file = new File(file.getAbsolutePath() + ".csv");

        try (PrintWriter pw = new PrintWriter(new OutputStreamWriter(new FileOutputStream(file), "UTF-8"))) {
            // BOM for Excel UTF-8 recognition
            pw.print('\uFEFF');

            // Title rows
            pw.println("EMS Pro - Employee Report");
            pw.println("Generated: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy  hh:mm a")));
            pw.println("Generated By: " + SessionManager.username + " (" + SessionManager.role + ")");
            pw.println();

            // Header row
            pw.println("Emp ID,Full Name,Father's Name,Designation,Department,Phone,Email,Salary,Education,Date of Birth,Aadhaar,Address,Joined Date,Status");

            // Data rows
            Connection conn = DBConnection.getConnection();
            ResultSet rs = conn.createStatement().executeQuery(
                "SELECT * FROM employee ORDER BY created_at DESC");

            int count = 0;
            while (rs.next()) {
                String joined = rs.getTimestamp("created_at") != null
                    ? rs.getTimestamp("created_at").toLocalDateTime().toLocalDate().toString() : "";
                pw.println(
                    esc(rs.getString("empId"))      + "," +
                    esc(rs.getString("name"))        + "," +
                    esc(rs.getString("fname"))       + "," +
                    esc(rs.getString("designation")) + "," +
                    esc(rs.getString("education"))   + "," +
                    esc(rs.getString("phone"))       + "," +
                    esc(rs.getString("email"))       + "," +
                    esc(rs.getString("salary"))      + "," +
                    esc(rs.getString("education"))   + "," +
                    esc(rs.getString("dob"))         + "," +
                    esc(rs.getString("aadhaar"))     + "," +
                    esc(rs.getString("address"))     + "," +
                    esc(joined)                      + "," +
                    "Active"
                );
                count++;
            }
            rs.close();

            // Summary footer
            pw.println();
            pw.println("Total Employees:," + count);

            // Attendance summary
            pw.println();
            pw.println("ATTENDANCE SUMMARY (Today)");
            pw.println("Emp ID,Name,Status,Check In,Check Out");
            String today = LocalDate.now().toString();
            ResultSet ar = conn.createStatement().executeQuery(
                "SELECT e.empId,e.name,a.status,a.checkIn,a.checkOut " +
                "FROM employee e LEFT JOIN attendance a ON e.empId=a.empId AND a.date='" + today + "' " +
                "ORDER BY e.name");
            while(ar.next()){
                pw.println(
                    esc(ar.getString("empId"))   + "," +
                    esc(ar.getString("name"))    + "," +
                    esc(ar.getString("status"))  + "," +
                    esc(ar.getString("checkIn")) + "," +
                    esc(ar.getString("checkOut"))
                );
            }
            ar.close();

            showSuccess(parent, file, count);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(parent,
                "Export failed: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** Escape CSV field */
    private static String esc(String s) {
        if (s == null || s.isEmpty()) return "";
        if (s.contains(",") || s.contains("\"") || s.contains("\n"))
            return "\"" + s.replace("\"", "\"\"") + "\"";
        return s;
    }

    private static void showSuccess(JFrame parent, File file, int count) {
        JDialog d = new JDialog(parent, "Export Successful", true);
        d.setSize(400, 220); d.setLocationRelativeTo(parent);

        JPanel root = new JPanel(new BorderLayout());
        root.setBackground(Theme.BG_PANEL);
        root.setBorder(new EmptyBorder(24,28,24,28));

        JLabel icon = new JLabel("✓", SwingConstants.CENTER);
        icon.setFont(new Font("Segoe UI",Font.BOLD,36));
        icon.setForeground(Theme.ACCENT_GRN);

        JLabel msg1 = new JLabel("Export Successful!", SwingConstants.CENTER);
        msg1.setFont(new Font("Segoe UI",Font.BOLD,15));
        msg1.setForeground(Theme.TEXT_PRI);

        JLabel msg2 = new JLabel(count + " employees exported to Excel", SwingConstants.CENTER);
        msg2.setFont(Theme.FONT_MED); msg2.setForeground(Theme.TEXT_MUT);

        JLabel path = new JLabel(file.getName(), SwingConstants.CENTER);
        path.setFont(Theme.FONT_SMALL); path.setForeground(Theme.ACCENT_BLU);

        JPanel btns = new JPanel(new FlowLayout(FlowLayout.CENTER,8,0));
        btns.setBackground(Theme.BG_PANEL);

        UI.DarkButton open = UI.DarkButton.success("Open File");
        open.addActionListener(e -> {
            try { Desktop.getDesktop().open(file); } catch(Exception ex){}
            d.dispose();
        });
        UI.DarkButton close = UI.DarkButton.normal("Close");
        close.addActionListener(e -> d.dispose());
        btns.add(open); btns.add(close);

        JPanel center = new JPanel();
        center.setLayout(new BoxLayout(center, BoxLayout.Y_AXIS));
        center.setBackground(Theme.BG_PANEL);
        for(JComponent c : new JComponent[]{icon,msg1,msg2,path}){
            c.setAlignmentX(Component.CENTER_ALIGNMENT);
            center.add(c); center.add(Box.createVerticalStrut(6));
        }
        center.add(Box.createVerticalStrut(10)); center.add(btns);

        root.add(center, BorderLayout.CENTER);
        d.setContentPane(root); d.setVisible(true);

        NotificationManager.add("Export","Employee list exported to "+file.getName(),"info");
    }
}